"""
Streamlit chat app for the Parent-Child + Self-Query "fusion" retriever,
wrapped in a LangGraph agentic router (vector RAG vs. pandas aggregation vs. both)
with an LLM-as-judge self-correction loop.

Design notes (why this differs slightly from the exploratory notebook):

- The Chroma vector store is PERSISTENT (`persist_directory=CHROMA_DIR`) and the
  parent-document store is also persisted to disk (`LocalFileStore` instead of
  `InMemoryStore`). On startup we check whether the collection already has
  vectors; if it does, we skip re-reading the CSV and re-embedding entirely.
  This means the (expensive, API-billed) indexing step only ever runs once —
  every subsequent `streamlit run` reuses the existing on-disk index.

- `st.cache_resource` wraps every expensive object (embeddings, vectorstore,
  retrievers, the compiled graph) so Streamlit's rerun-on-every-interaction
  model doesn't reconstruct them on every keystroke/message.

- The compiled LangGraph app uses `InMemorySaver` as its checkpointer, as
  requested, so the graph has real checkpointing support. Each user turn is
  run on a *fresh* thread_id rather than one shared thread — `judge_feedback`
  uses an additive reducer (`Annotated[List[str], add]`), so reusing one
  thread across unrelated questions would make old feedback bleed into new
  runs (the additive reducer has no way to be reset mid-thread). The visible
  chat history shown in the UI is tracked separately in
  `st.session_state.chat_history`, so the conversation still reads as a
  normal chat even though each turn is graph-isolated.
"""

import os
import time
import uuid
import warnings
from operator import add
from typing import Annotated, List, Literal, TypedDict

import pandas as pd
import streamlit as st
from dotenv import load_dotenv
from pydantic import BaseModel, Field

from langchain_core.documents import Document
from langchain_core.messages import HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.retrievers import BaseRetriever

from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_chroma import Chroma

from langchain_classic.chains.query_constructor.ir import Comparison
from langchain_classic.chains.query_constructor.schema import AttributeInfo
from langchain_classic.retrievers import ContextualCompressionRetriever, ParentDocumentRetriever, SelfQueryRetriever
from langchain_classic.retrievers.document_compressors import (
    DocumentCompressorPipeline,
    EmbeddingsFilter,
    LLMChainExtractor,
)
from langchain_classic.storage import LocalFileStore, create_kv_docstore
from langchain_community.query_constructors.chroma import ChromaTranslator
from langchain_experimental.agents import create_pandas_dataframe_agent
from langchain_text_splitters import RecursiveCharacterTextSplitter

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph

warnings.filterwarnings("ignore")
load_dotenv()

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
CHROMA_DIR = os.path.join(BASE_DIR, "chroma_store")
PARENT_STORE_DIR = os.path.join(BASE_DIR, "parent_store")
DEFAULT_CSV_PATH = os.path.join(BASE_DIR, "data", "campaign_intelligence_sample.csv")

MAIN_MODEL = os.getenv("MAIN_MODEL", "gpt-4.1")
AGENT_MODEL = os.getenv("AGENT_MODEL", "gpt-4.1-mini")
JUDGE_MODEL = os.getenv("JUDGE_MODEL", "gpt-4.1-mini")
MAX_JUDGE_TRIES = 3

COLUMNS = [
    "campaign_id", "territory", "quarter", "cohort", "event_description",
    "cross_group_description", "reactivation_description", "final_insight",
    "combined_description", "revenue", "tg_count", "cg_count",
    "lift_percent", "response_rate_percent", "atbms",
]

METADATA_FIELD_INFO = [
    AttributeInfo(name="campaign_id", description="Unique campaign identifier, e.g. 'CMP1001', 'CMP1002'", type="string"),
    AttributeInfo(name="territory", description="Geographic territory of the campaign. One of: 'North', 'South', 'East', 'West', 'Central'", type="string"),
    AttributeInfo(name="quarter", description="Fiscal quarter in which the campaign ran. One of: 'Q1', 'Q2', 'Q3', 'Q4'", type="string"),
    AttributeInfo(name="cohort", description="Customer cohort/segment targeted by the campaign. One of: 'New User', 'Price Sensitive', 'Dormant', 'High Value', 'Frequent Buyer'", type="string"),
    AttributeInfo(name="revenue", description="Total revenue generated by the campaign (in currency units), ranges roughly 50000 to 900000", type="float"),
    AttributeInfo(name="tg_count", description="Target group customer count for the campaign, ranges roughly 5000 to 50000", type="integer"),
    AttributeInfo(name="cg_count", description="Control group customer count for the campaign, ranges roughly 2000 to 20000", type="integer"),
    AttributeInfo(name="lift_percent", description="Incremental lift percentage of target group vs control group, ranges roughly -5 to 35", type="float"),
    AttributeInfo(name="response_rate_percent", description="Campaign response rate percentage, ranges roughly 1.5 to 22", type="float"),
    AttributeInfo(name="atbms", description="Average transaction basket / metric score for the campaign, ranges roughly 300 to 2500", type="float"),
]

DOCUMENT_CONTENT_DESCRIPTION = (
    "Campaign intelligence summaries combining event description, cross-group analysis, "
    "reactivation insights, and final recommendation for marketing campaigns across territories."
)


# ---------------------------------------------------------------------------
# Retriever plumbing (Self-Query filter safety + Parent-Child fusion)
# ---------------------------------------------------------------------------
class SafeChromaTranslator(ChromaTranslator):
    """Coerces numpy/pandas scalar filter values to native Python int/float
    before Chroma validates the `where` clause."""

    def visit_comparison(self, comparison: Comparison) -> dict:
        value = comparison.value
        if isinstance(value, (int, float)) or hasattr(value, "item"):
            try:
                value = float(value) if isinstance(value, float) or hasattr(value, "item") else int(value)
            except (TypeError, ValueError):
                pass
            comparison = Comparison(comparator=comparison.comparator, attribute=comparison.attribute, value=value)
        return super().visit_comparison(comparison)


class SelfQueryParentChildRetriver(BaseRetriever):
    """Runs Self-Query retrieval over child chunks, then resolves each hit
    back to its full parent Document."""

    SelfQueryRetriever: BaseRetriever
    parent_docstore: object

    def _get_relevant_documents(self, query: str) -> List[Document]:
        child_docs = self.SelfQueryRetriever.invoke(query)
        parent_ids = {doc.metadata["doc_id"] for doc in child_docs if "doc_id" in doc.metadata}
        parent_docs = [self.parent_docstore.mget([pid])[0] for pid in parent_ids]
        return [d for d in parent_docs if d is not None]


def build_documents(df: pd.DataFrame) -> List[Document]:
    docs = []
    for _, row in df.iterrows():
        docs.append(
            Document(
                page_content=row["combined_description"],
                metadata={
                    "campaign_id": row["campaign_id"],
                    "territory": row["territory"],
                    "quarter": row["quarter"],
                    "cohort": row["cohort"],
                    "revenue": float(row["revenue"]),
                    "tg_count": int(row["tg_count"]),
                    "cg_count": int(row["cg_count"]),
                    "lift_percent": float(row["lift_percent"]),
                    "response_rate_percent": float(row["response_rate_percent"]),
                    "atbms": float(row["atbms"]),
                },
            )
        )
    return docs


# ---------------------------------------------------------------------------
# Cached resources — built once per Streamlit server process
# ---------------------------------------------------------------------------
@st.cache_resource(show_spinner="Connecting models...")
def get_models():
    return {
        "main": ChatOpenAI(model=MAIN_MODEL),
        "agent": ChatOpenAI(model=AGENT_MODEL),
        "judge": ChatOpenAI(model=JUDGE_MODEL),
        "embeddings": OpenAIEmbeddings(),
    }


@st.cache_resource(show_spinner="Opening persistent Chroma store...")
def get_vectorstore(_embeddings) -> Chroma:
    """Persistent Chroma collection — survives app restarts. Only populated
    (embedded) the first time it's empty; never rebuilt after that."""
    return Chroma(
        collection_name="campaign_intel",
        embedding_function=_embeddings,
        persist_directory=CHROMA_DIR,
    )


@st.cache_resource(show_spinner="Indexing campaign data (first run only — subsequent runs reuse the persisted index)...")
def build_index_and_retrievers(csv_path: str):
    models = get_models()
    vectorstore = get_vectorstore(models["embeddings"])

    parent_docstore = create_kv_docstore(LocalFileStore(PARENT_STORE_DIR))

    p_splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=100)
    c_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=50)

    parent_child_retriever = ParentDocumentRetriever(
        parent_splitter=p_splitter,
        child_splitter=c_splitter,
        docstore=parent_docstore,
        vectorstore=vectorstore,
    )

    already_indexed = vectorstore._collection.count() > 0
    df = None
    if not already_indexed:
        if not os.path.exists(csv_path):
            raise FileNotFoundError(
                f"No persisted index found at '{CHROMA_DIR}', and the source CSV "
                f"'{csv_path}' does not exist. Provide the CSV once so the index "
                f"can be built — future runs will not need it."
            )
        df = pd.read_csv(csv_path)
        parent_child_retriever.add_documents(build_documents(df))
    else:
        # Index already on disk — no CSV read, no embedding calls.
        df = pd.read_csv(csv_path) if os.path.exists(csv_path) else None

    self_query_retriever = SelfQueryRetriever.from_llm(
        llm=models["main"],
        vectorstore=vectorstore,
        metadata_field_info=METADATA_FIELD_INFO,
        structured_query_translator=SafeChromaTranslator(),
        document_contents=DOCUMENT_CONTENT_DESCRIPTION,
        search_type="mmr",
        search_kwargs={"k": 10, "lambda_mult": 0.5, "fetch_k": 30},
    )

    custom_retriever = SelfQueryParentChildRetriver(
        SelfQueryRetriever=self_query_retriever,
        parent_docstore=parent_docstore,
    )

    llm_extract_compressor = LLMChainExtractor.from_llm(llm=models["main"])
    filter_compressor = EmbeddingsFilter(embeddings=models["embeddings"], similarity_threshold=0.65)
    compressor_pipeline = DocumentCompressorPipeline(transformers=[filter_compressor, llm_extract_compressor])
    compression_retriever = ContextualCompressionRetriever(
        base_compressor=compressor_pipeline,
        base_retriever=custom_retriever,
    )

    return {
        "vectorstore": vectorstore,
        "custom_retriever": custom_retriever,
        "compression_retriever": compression_retriever,
        "df": df,
        "chunk_count": vectorstore._collection.count(),
    }


# ---------------------------------------------------------------------------
# LangGraph state + schemas
# ---------------------------------------------------------------------------
class RagSchema(TypedDict):
    query: str
    context: str
    augmented_question: object
    decison: str
    agent_ans: str
    final_ans: str
    pandas_query: str
    regular_query: str
    verdict: str
    judge_decison: str
    judge_feedback: Annotated[List[str], add]
    max_try: int


class JudgeSchema(BaseModel):
    judge_decison: Literal["Rework", "Good"] = Field(description="If the answer is grounded then good else rework")
    judge_feedback: str = Field(description="Why the decision was taken and what improvement is needed")


class Deciosn(BaseModel):
    decison: Literal["Agent", "Regular", "Both"] = Field(
        description="Whether the query should go to the Agent (pandas) path, the Regular RAG path, or Both"
    )
    verdict: str = Field(description="Why this decision was taken")
    pandas_query: str
    regular_query: str


SYSTEM_PROMPT_REGULAR = """You are a rag agent
    -See the context and question given by the customer
    - answer only gounded truth you are getting from the context
    - If you don't see context which support the question say you don't know stritly"""

SYSTEM_PROMPT_AGENT = """You are a data analyst assistant.
- You are given a computed answer (from a pandas aggregation) along with the pandas query used.
- Your job is to present this computed answer clearly and confidently to the user in natural language.
- The computed answer IS the ground truth — do not second-guess it or say "I don't know" if a computed value is present.
- If Any number is there return the number in a natrual lanugae as per the query given.
- No assumtion should make without fact support
- only data driven insight nothing extra"""


def build_graph(retrievers: dict):
    models = get_models()
    model = models["main"]
    compression_retriever = retrievers["compression_retriever"]
    df = retrievers["df"]

    def make_pandas_agent():
        return create_pandas_dataframe_agent(
            llm=models["agent"],
            df=df,
            allow_dangerous_code=True,
            prefix=f"""You are a data analyst. Given the dataframe columns:
                {COLUMNS}
                write a pandas expression to answer the user's question.""",
        )

    def DecionNode(state: RagSchema):
        struct_llm = models["agent"].with_structured_output(Deciosn)
        system_prompt = f"""You are a query analyzer deciding whether the query should go to the pandas
        Agent path or the regular RAG path.
        - Break the query into a pandas-style sub-question for anything needing aggregation/comparison
          ('compare', 'greater than', 'which is the best', etc.)
        - The RAG system CANNOT answer aggregation-type questions — if you see any aggregation, return Agent strictly.
        - Column list: {COLUMNS}
        - If the query mixes both types, return Both, and draft both pandas_query and regular_query."""
        prompt = ChatPromptTemplate.from_messages(
            [("system", system_prompt), ("human", "Question : \n {question}")]
        )
        r = struct_llm.invoke(prompt.invoke({"question": state["query"]}))
        return {
            "decison": r.decison,
            "verdict": r.verdict,
            "pandas_query": r.pandas_query,
            "regular_query": r.regular_query,
        }

    def Deciosn_Router_final(state: RagSchema):
        return "Agent_Execution" if state["decison"] == "Agent" else "retriver_node"

    def retriver_node(state: RagSchema):
        context = "\n\n...\n".join(
            i.page_content for i in compression_retriever.invoke(state["query"]) if i.page_content is not None
        )
        return {"context": context}

    def Regular_Augmentation(state: RagSchema):
        prompt = ChatPromptTemplate.from_messages(
            [("system", SYSTEM_PROMPT_REGULAR), ("human", "Context :\n{context} \n\nQuestion \n{question}")]
        )
        return {"augmented_question": prompt.invoke({"context": state["context"], "question": state["query"]})}

    def Agent_Execution(state: RagSchema):
        result = make_pandas_agent().invoke(state["query"])
        return {"agent_ans": result.get("output", "No result found")}

    def combine_node(state: RagSchema):
        pandas_query = state["pandas_query"]
        result_pandas_raw = make_pandas_agent().invoke(
            f"Original query is: {state['query']} the modified query for you is {pandas_query} "
            f"answer wisely for the part of the query where you need this pandas query reference "
            f"if the aggregated part is there and pandas query is not blank"
        )
        result_pandas = result_pandas_raw.get("output", "No result found")
        context = state["context"] + "\n\n **Aggregated part of the query answer is given below**\n\n" + result_pandas

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """You are a data analyst assistant. You are given two pieces of information:
            1. Retrieved context (qualitative campaign descriptions)
            2. A computed data answer (from pandas aggregation/comparison)

            Your job: Answer the user's FULL question using BOTH pieces of information.
            - If the question has multiple parts (e.g., a comparison AND a descriptive part),
            make sure your answer addresses EVERY part.
            - Use the computed answer for any numeric/comparison claims.
            - Use the retrieved context for descriptive/qualitative claims.
            - Do not omit any part of the original question.""",
                ),
                (
                    "human",
                    "Retrieved Context:\n{context}\n\nOriginal Question:\n{question}\n\n"
                    "Provide a complete answer covering all parts of the question.",
                ),
            ]
        )
        augmented_question = prompt.invoke({"context": context, "question": state["query"]})
        return {"augmented_question": augmented_question, "agent_ans": result_pandas}

    def Agent_Augmentation(state: RagSchema):
        prompt = ChatPromptTemplate.from_messages(
            [
                ("system", SYSTEM_PROMPT_AGENT),
                ("human", "Context :\n{context} \n\nQuestion \n{question} \n\n Pandas Query : {pandas_query}"),
            ]
        )
        return {
            "augmented_question": prompt.invoke(
                {"context": state["agent_ans"], "question": state["query"], "pandas_query": state["pandas_query"]}
            )
        }

    def Retrive_router(state: RagSchema):
        return "combine_node" if state["decison"] == "Both" else "Regular_Augmentation"

    def LLm_AS_judge(state: RagSchema):
        judge_llm = models["judge"].with_structured_output(JudgeSchema)
        max_try = state.get("max_try", 0)

        if max_try <= 2:
            prompt = ChatPromptTemplate.from_messages(
                [
                    (
                        "system",
                        """You are a Rag System final answer evaluator. See the query, context, and agent answer
            and evaluate whether the answer is grounded; if not, give feedback to the generator.
            - Sometimes agent answer can be None, sometimes context can be None.
            - If context is blank, treat the Agent Answer as the context (noting it came from a pandas tool call).
            - If both context and agent answer are blank, say you don't have an idea.
            - If both are present, treat context as the combination of both — never drop the aggregated part.
            - Output structure should be bullet points, one per paragraph.""",
                    ),
                    (
                        "human",
                        "Context: \n{Context},\n"
                        "Agent Answer: \n{agent_ans},\n"
                        "Question : {query} -> Pandas Part {pandas_query} -> Regular Query part {reqular_query}",
                    ),
                ]
            )
            chain = prompt | judge_llm
            result = chain.invoke(
                {
                    "Context": state.get("context", "No context"),
                    "agent_ans": state.get("agent_ans", None),
                    "query": state["query"],
                    "pandas_query": state.get("pandas_query", "Not found"),
                    "reqular_query": state.get("regular_query", "Not found"),
                }
            )
            return {
                "judge_decison": result.judge_decison,
                "judge_feedback": [result.judge_feedback],
                "max_try": max_try + 1,
            }
        return {"judge_decison": "Good", "judge_feedback": [""], "max_try": max_try}

    def route_judge(state: RagSchema):
        return END if state["judge_decison"] == "Good" else "Generation"

    def Generation(state: RagSchema):
        max_try = state.get("max_try", 0)
        feedback_list = state.get("judge_feedback", [])
        feedback = "\n\n...\n".join(feedback_list)

        aug_q_base = state["augmented_question"]
        if hasattr(aug_q_base, "to_messages"):
            aug_q_base = aug_q_base.to_messages()

        if len(feedback) >= 5 and max_try <= 2:
            feedback_msg = HumanMessage(
                content="The upper response is not enough, the Judge has passed feedback, see that and "
                "correct that.\nJudge Feedback \n" + feedback
            )
            aug_q = aug_q_base + [feedback_msg]
        else:
            aug_q = aug_q_base

        response = model.invoke(aug_q)
        return {"final_ans": response.content}

    builder = StateGraph(RagSchema)
    builder.add_node("DecionNode", DecionNode)
    builder.add_node("retriver_node", retriver_node)
    builder.add_node("Regular_Augmentation", Regular_Augmentation)
    builder.add_node("Agent_Augmentation", Agent_Augmentation)
    builder.add_node("Generation", Generation)
    builder.add_node("Agent_Execution", Agent_Execution)
    builder.add_node("combine_node", combine_node)
    builder.add_node("LLm_AS_judge", LLm_AS_judge)

    builder.add_edge(START, "DecionNode")
    builder.add_conditional_edges(
        "DecionNode", Deciosn_Router_final, {"retriver_node": "retriver_node", "Agent_Execution": "Agent_Execution"}
    )
    builder.add_conditional_edges(
        "retriver_node", Retrive_router, {"Regular_Augmentation": "Regular_Augmentation", "combine_node": "combine_node"}
    )
    builder.add_edge("Regular_Augmentation", "Generation")
    builder.add_edge("Agent_Execution", "Agent_Augmentation")
    builder.add_edge("Agent_Augmentation", "Generation")
    builder.add_edge("combine_node", "Generation")
    builder.add_edge("Generation", "LLm_AS_judge")
    builder.add_conditional_edges("LLm_AS_judge", route_judge, {END: END, "Generation": "Generation"})

    # In-memory checkpointer, wired at compile time as requested — gives the
    # graph real checkpointing/thread support (see module docstring for why
    # each chat turn still runs on its own fresh thread_id).
    return builder.compile(checkpointer=InMemorySaver())


@st.cache_resource(show_spinner="Compiling the agentic RAG graph...")
def get_app(csv_path: str):
    retrievers = build_index_and_retrievers(csv_path)
    graph = build_graph(retrievers)
    return graph, retrievers


# ---------------------------------------------------------------------------
# Streamlit UI
# ---------------------------------------------------------------------------
st.set_page_config(page_title="Agentic RAG — Parent-Child + Self-Query Fusion", page_icon="📊", layout="wide")

st.title("📊 Campaign Intelligence — Agentic RAG")
st.caption(
    "Self-Query + Parent-Child fusion retriever, routed by a LangGraph agent between vector RAG, "
    "a pandas aggregation agent, or both — with an LLM-as-judge self-correction loop."
)

with st.sidebar:
    st.header("⚙️ Setup")
    csv_path = st.text_input("Source CSV (only needed for first-time indexing)", value=DEFAULT_CSV_PATH)
    st.caption(f"Persistent Chroma dir: `{CHROMA_DIR}`")
    st.caption(f"Persistent parent-doc dir: `{PARENT_STORE_DIR}`")

    if not os.getenv("OPENAI_API_KEY"):
        st.warning("OPENAI_API_KEY is not set — add it to your .env file before querying.")

    if st.button("🗑️ Clear chat"):
        st.session_state.chat_history = []
        st.rerun()

if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

try:
    app, retrievers = get_app(csv_path)
    with st.sidebar:
        st.success(f"Index ready — {retrievers['chunk_count']} child chunks in Chroma.")
except Exception as exc:  # surfaced to the user instead of crashing the whole app
    st.error(f"Failed to initialize the retrieval index: {exc}")
    st.stop()

for turn in st.session_state.chat_history:
    with st.chat_message("user"):
        st.markdown(turn["query"])
    with st.chat_message("assistant"):
        st.markdown(turn["final_ans"])
        with st.expander("Debug: routing & judge trace"):
            st.markdown(f"**Decision:** `{turn['decison']}`  \n**Verdict:** {turn['verdict']}")
            if turn.get("pandas_query"):
                st.code(turn["pandas_query"], language="python")
            st.markdown(f"**Judge iterations:** {turn['max_try']}")
            for i, fb in enumerate([f for f in turn["judge_feedback"] if f], 1):
                st.markdown(f"*Round {i} feedback:* {fb}")
            st.markdown(f"**Latency:** {turn['latency']:.1f}s")

user_query = st.chat_input("Ask about campaign performance, comparisons, or specific campaigns...")
if user_query:
    with st.chat_message("user"):
        st.markdown(user_query)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            start = time.time()
            # Fresh thread per turn — see module docstring for the reducer-bleed reasoning.
            thread_id = str(uuid.uuid4())
            result = app.invoke(
                {"query": user_query, "max_try": 0, "judge_feedback": []},
                config={"configurable": {"thread_id": thread_id}},
            )
            latency = time.time() - start
        st.markdown(result["final_ans"])
        with st.expander("Debug: routing & judge trace"):
            st.markdown(f"**Decision:** `{result['decison']}`  \n**Verdict:** {result['verdict']}")
            if result.get("pandas_query"):
                st.code(result["pandas_query"], language="python")
            st.markdown(f"**Judge iterations:** {result['max_try']}")
            for i, fb in enumerate([f for f in result["judge_feedback"] if f], 1):
                st.markdown(f"*Round {i} feedback:* {fb}")
            st.markdown(f"**Latency:** {latency:.1f}s")

    st.session_state.chat_history.append(
        {
            "query": user_query,
            "final_ans": result["final_ans"],
            "decison": result["decison"],
            "verdict": result["verdict"],
            "pandas_query": result.get("pandas_query", ""),
            "max_try": result["max_try"],
            "judge_feedback": result["judge_feedback"],
            "latency": latency,
        }
    )
